# Generated by Django 4.1.6 on 2023-02-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
