# Generated by Django 4.1.6 on 2023-02-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
