# Generated by Django 4.1.6 on 2023-02-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
