# Generated by Django 4.1.6 on 2023-02-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
