# Generated by Django 4.1.6 on 2023-02-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
