# Generated by Django 4.1.6 on 2023-02-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
