# Generated by Django 4.1.6 on 2023-02-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
