# Generated by Django 4.1.6 on 2023-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0006_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Place', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Type', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('User', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Value', models.IntegerField(default=0)),
                ('Syllabus', models.FileField(upload_to='')),
                ('Date', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
            ],
        ),
    ]
