# Generated by Django 4.1.6 on 2023-02-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
