# Generated by Django 4.1.6 on 2023-02-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_syllabus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
