# Generated by Django 4.1.6 on 2023-02-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_delete_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Teacher', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Syllabus', models.FileField(upload_to='media')),
            ],
        ),
    ]
